# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d884847c90273e66e8f50aaac3be6ef8c4c54c44c461358adda9f2a0815ebdfdef7f780be84aa80f793507f8dfc3f29ded61cd79da25924cda59ee39628d7c3

test:
  secret_key_base: b23af6973a50ec48d2dcabba0cdf57061c27701cb53624eff657ce62918f7a9872d38c78cce58199c0ccc7f92f4c3e09ae97ebf5ba84fc9472aabe0e4ec511e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
